### ISSUE TITLE
1.14.1 Update broke Fluffychat on iOS/iPad OS, shows grey uninteractable screen on load.

### ISSUE THREAD

**Issue by aneverhopefulhelper** [krille-chan/fluffychat#582] opened 2023-09-19 00:22 UTC
### Bug Description

On iPad OS 17 in Fluffychat 1.14.1 when trying to get into the app the lock screen just shows as grey with no input possible.

### Steps to Reproduce

1. Open App
2. Be met with a grey featureless screen
3. Try to interact
4. Nothing happens

### Expected Behavior

I expect to see the lockscreen and be able to log in to fluffychat but that is not possible

### App Version

1.14.1

### Additional Platform Information

iPad OS 17

### Additional Context

1.14.0 had a working lockscreen, so it's whatever was changed in 1.14.1 that causes the issue.

**Comment by leematos** [comment] 2023-09-20 14:07
Seeing the same on iOS 16.6 on an iPhone 14 Pro

**Comment by 0xpr03** [comment] 2023-09-20 18:09
Same here with Android 10. 1.14.1 breaks things with lockscreen + multi acc setup. I still get push notifs, can see that network traffic happens when I open it, but everything stays grey.

**Comment by aneverhopefulhelper** [comment] 2023-09-20 20:38
I too have multi-account setup, so that might be the issue in part?

**Comment by reinhart1010** [comment] 2023-09-21 06:36
Not really, I can run the updated app normally.

![image](https://github.com/krille-chan/fluffychat/assets/17312341/f4a8c568-7c78-418d-8cb2-3d94057d9d08)
![image](https://github.com/krille-chan/fluffychat/assets/17312341/c130f609-879f-46b0-a2b7-48cfda20707e)

**Comment by leematos** [comment] 2023-09-21 11:55
@reinhart1010 -- I think the difference may be that you have multiple accounts?

@aneverhopefulhelper -- do you have multiple accounts in fluffy? I do not.

**Comment by krille-chan** [comment] 2023-09-21 12:07
Is it fixed by not using the applock?

**Comment by aneverhopefulhelper** [comment] 2023-09-21 12:29
> Is it fixed by not using the applock?

I have no idea since I can't get in to it to turn it off. Since this broken lockscreen is preventing me from doing so.

**Comment by aneverhopefulhelper** [comment] 2023-09-21 12:30
> @reinhart1010 -- I think the difference may be that you have multiple accounts?
> 
> @aneverhopefulhelper -- do you have multiple accounts in fluffy? I do not.

I do have multiple accounts as I stated in the comments earlier.

**Comment by leematos** [comment] 2023-09-21 22:17
Same for me @krille-chan -- nothing beyond a grey screen on launch. I did have app lock on, so it seems like you have some idea of what the problem is :)

**Comment by krille-chan** [comment] 2023-09-22 06:28
Fixed in latest commit. I will push a new version soon

**Comment by aneverhopefulhelper** [comment] 2023-09-28 00:33
Can confirm it works and a lot better than the previous lockscreens/applock too! Thank you @krille-chan

**Closed** 2023-09-28 05:57 UTC
