### ISSUE TITLE
Turning the phone = Crash

### ISSUE THREAD

**Issue by lKomentatorl** [krille-chan/fluffychat#1032] opened 2024-04-19 08:03 UTC
### Bug Description

When you turn the phone twice on an iPhone, from horizontal to vertical, it crashes

### Steps to Reproduce

1. Revert to horizontal format
2. Revert to vertical format
3. Crash report 

### Expected Behavior

Sure

### App Version

1.19.0

### Additional Platform Information

iPhone XS

**Comment by Haui1112** [comment] 2024-04-19 11:18
Should also be a duplicate of #974 (I have the same issue btw.)

**Closed** 2024-04-19 11:46 UTC
Labels: bug
