### ISSUE TITLE
RTL: Chat Bubbles UI is Very Messed Up

### ISSUE THREAD

**Issue by krille-chan** [krille-chan/fluffychat#365] opened 2023-07-15 00:17 UTC
I inserted this as a sidenote in another issue #646 a long time ago. I should have made it its own issue.

#### Description

Text bubble alignment is opposite what it should be when in RTL.  Other users' avatars are on the right, whereas text bubbles are left-aligned and the squared corner is also on the left, away from their avatars.
![Screenshot_۲۰۲۱۱۱۱۳-۱۷۱۲۳۶](/uploads/14623488031c31dd9aa205cf6502ec12/Screenshot_۲۰۲۱۱۱۱۳-۱۷۱۲۳۶.jpg)
![Screenshot_۲۰۲۱۱۱۱۳-۱۷۲۳۱۸](/uploads/30b9efc3182acf5bd71e3d402b8052ad/Screenshot_۲۰۲۱۱۱۱۳-۱۷۲۳۱۸.jpg)

#### To Reproduce
Put device in an RTL language and look at the text bubbles.

#### Additional information:
- Device: Samsung GS20
- OS and OS version: Android ~~11~~ 12
- Installed version of FluffyChat:  latest nightly ~~0.42.2~~ ~~1.2.0~~ 1.4.0
- (Android only) Which store are you using: fdroid 
- (Android only) Are Google Services available: available, but I'm using gotify-up

**Comment by FarisZR** [comment] 2023-10-23 10:21
Any updates on this? it's fine if the App doesn't support an RTL layout, crucially the Text order has to work for it to be usable, as currently it's unusable for people speaking English and any RTL language like Arabic.

**Comment by FarisZR** [comment] 2023-10-23 10:23
it seems to be fixed if the app is in arabic, but the issue is when the app is in LTR mode, but the text is RTL, it stays LTR.

**Comment by FarisZR** [comment] 2024-02-21 08:44
Doesn't mean it's not still an issue.

-------- Ursprüngliche Nachricht --------
Am 21.02.24 02:48 um github-actions[bot] - notifications at github.com schrieb :

**Comment by Mikaela** [comment] 2024-03-07 16:20
Duplicate of #63.

**Closed by Mikaela** 2024-03-07 16:20 UTC
