### ISSUE TITLE
Thread support

### ISSUE THREAD

**Issue by Ilovetoocode** [krille-chan/fluffychat#1288] opened 2024-08-17 20:47 UTC
### Feature Description

Matrix has threading capabilities in it that, as far as I see, Fluffychat hasn't properly implimented. Messages from within threads all get sent into one massive thread in the chat instead.

### Rationale

Threading is a native feature of Matrix, one that people that use other cleints use due to them implimenting it correctly. The implimentation as is has broken a bot used for auctions in a server I'm in.

**Comment by Mikaela** [comment] 2024-08-18 03:44
Duplicate of #497.

**Closed by Mikaela** 2024-08-18 03:44 UTC
Labels: enhancement
