### ISSUE TITLE
IOS can not build

### ISSUE THREAD

**Issue by rhymelph** [krille-chan/fluffychat#697] opened 2023-11-24 00:50 UTC
### Bug Description

```
Could not build the precompiled application for the device.
Lexical or Preprocessor Issue (Xcode): 'olm/olm_export.h' file not found
/Users/rhyme/Documents/flutter_project/dzy/sola/plugins/flutter_olm/ios/include/olm/error.h:17:9
```

### Steps to Reproduce

flutter build ios

### Expected Behavior

```
Could not build the precompiled application for the device.
Lexical or Preprocessor Issue (Xcode): 'olm/olm_export.h' file not found
/Users/rhyme/Documents/flutter_project/dzy/sola/plugins/flutter_olm/ios/include/olm/error.h:17:9
```

### App Version

new version

### Additional Platform Information

IOS

**Comment by krille-chan** [comment] 2024-01-14 06:35
I cannot reproduce this. Please try to clear the cache. Closed as it works in ci and on my local machine

**Closed by krille-chan** 2024-01-14 06:35 UTC
Labels: bug
