### ISSUE TITLE
RTL formatting 

### ISSUE THREAD

**Issue by amirrezaeng** [krille-chan/fluffychat#930] opened 2024-03-07 06:28 UTC
### Feature Description

Hi
Right To Left formatting for complex scripts, such as Persian and Arabic language is not fully supported and needs to be done.

### Rationale

There are many users in Iran who want to use fluffychat and lack of this feature is annoying. This problem exist also for Arabic typing. I know Element itself has this problem too, but schildichat doesn't have this problem and RTL formatting is fully supported for Persian and Arabic languages.

### Mockup

I put two screenshots, one of them is fluffychat which doesn't support RTL formatting and schildichat which support RTL formatting.
![fluffychat](https://github.com/krille-chan/fluffychat/assets/40317893/f05ddbf6-abf5-41af-a529-0ec2f75580e0)
![schildichat](https://github.com/krille-chan/fluffychat/assets/40317893/7348ffe8-03eb-4d24-862d-cc4f9cc26957)

### Additional Context

Many languages scripts like Persian l, Arabic, Hebrew and so on, are written Right To Left and this feature should be enabled for the best results and correctly justifying in right side.

**Comment by Mikaela** [comment] 2024-03-07 16:21
Duplicate of #63.

**Closed by Mikaela** 2024-03-07 16:21 UTC
Labels: enhancement

**Comment by nazbooks** [comment] 2024-07-07 12:07
pleas add rtl support.
