### ISSUE TITLE
Link preview

### ISSUE THREAD

**Issue by SpiritOTHawk** [krille-chan/fluffychat#1162] opened 2024-06-04 14:37 UTC
### Feature Description

Add link previews to unencrypted chats, such as public groups.

### Rationale

This would be a handy feature that wouldn't break privacy in public chats, but wouldn't be present in private chats.

**Comment by Mikaela** [comment] 2024-06-08 13:30
Duplicate of #18.

**Closed by Mikaela** 2024-06-08 13:30 UTC
Labels: enhancement
