### ISSUE TITLE
[BUG]: Unable to play audio message

### ISSUE THREAD

**Issue by Happyfeet01** [krille-chan/fluffychat#875] opened 2024-02-07 09:28 UTC
- Operating system: ios
- Version: 1.17.3

### Exception
MissingPluginException(No implementation found for method play on channel com.ryanheise.just_audio.methods.af20d4fb-306a-4054-98c9-475879b38204)

### StackTrace
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320)
<asynchronous suspension>
#1      MethodChannelAudioPlayer.play (package:just_audio_platform_interface/method_channel_just_audio.dart:64)
<asynchronous suspension>
#2      AudioPlayer._sendPlayRequest (package:just_audio/just_audio.dart:981)
<asynchronous suspension>

**Comment by PgBiel** [comment] 2024-02-08 21:24
duplicate of #818

**Closed** 2024-02-08 21:34 UTC
