### ISSUE TITLE
push notifications with multiple accounts

### ISSUE THREAD

**Issue by camelCaseNick** [krille-chan/fluffychat#599] opened 2023-10-04 19:30 UTC
### Bug Description

Only push notifications for the first account seem to be registered with a UnifiedPush provider (at least ntfy) on Android.

### Steps to Reproduce

1. Install FluffyChat and ntfy.sh from F-Droid,
2. login to at least two matrix accounts in FluffyChat,
3. activate push notifications for multiple accounts,
4. notice only the first account lists a Device in the notifications panel of the settings,
5. ensure FluffyChat stays open in background,
6. send a message to a room with the first account,
7. receive a notification,
8. send a message to a room with another account, and
9. receive no notification.

### Expected Behavior

At step 4, FluffyChat should instead show a Device for each account. And step 9 should be the same as 7, meaning a push notification should be received for any account with FluffyChat running in background.

### App Version

1.14.2

### Additional Platform Information

Huawei's EMUI / Android 8.0

**Comment by John4266** [comment] 2023-10-13 20:16
Can confirm I am also having this issue.
Applies to both google services and UnifiedPush (ntfy).

Using 2 accounts, only receiving push notifications from the first logged in account.

Samsung S20 / Android 10
FluffyChat version 1.14.4 (google play store)

**Comment by jivanpal** [comment] 2023-10-19 20:11
Looks like a duplicate of #544.

**Closed** 2023-10-19 22:33 UTC
