### ISSUE TITLE
FluffyChat not available in my region (France!) on PlayStore

### ISSUE THREAD

**Issue by tobiasBora** [krille-chan/fluffychat#1126] opened 2024-05-21 12:27 UTC
### Bug Description

When searching for FluffyChat in the PlayStore, I get an error saying that this app is not available in my region. My region being France in Europe, I'm quite surprised.

### Steps to Reproduce

1. Goto the playstore from France
2. search for FluffyChat

### Expected Behavior

I expect it to be present

### App Version

latest on the play store

### Additional Platform Information

Android 11, google play updated on 1st june 2023

**Comment by TGRush** [comment] 2024-05-22 14:31
As this is not a bug with the software itself and more of a distribution problem, I recommend joining [`#fluffychat:matrix.org`](https://matrix.to/#/#fluffychat:matrix.org) and starting a discussion there.

**Comment by Mikaela** [comment] 2024-05-25 13:17
Duplicate of #76.

**Closed by Mikaela** 2024-05-25 13:17 UTC
Labels: bug
