### ISSUE TITLE
Flatpak release doesn't init database

### ISSUE THREAD

**Issue by NyaomiDEV** [krille-chan/fluffychat#972] opened 2024-04-01 22:31 UTC
### Bug Description

![image](https://github.com/krille-chan/fluffychat/assets/13177694/631ad680-b596-485b-822e-166fd95ff2da)

### Steps to Reproduce

1. Install FluffyChat from Flatpak
2. Observe issue

### Expected Behavior

I should see no errors upon clean installation

### App Version

1.19.0

### Additional Platform Information

PC with Artix Linux / Flatpak

**Comment by YokaiRick** [comment] 2024-04-02 16:24
it also can't open the old db, it throws you with an exeption to the login screen, and there i can't log in anymore.
Here are some exeptions, if you need more, pls ping me :D
```
** (fluffychat:2): WARNING **: 18:16:55.831: libsecret_error: `>\xbd\xae\xbeW
flutter: [Matrix] Unable to init database encryption - FormatException: Unexpected extension byte (at offset 2)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1741)
#1      Utf8Decoder.convert (dart:convert/utf.dart:349)
#2      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:502)
#3      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:477)
#4      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:647)
#5      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
** (fluffychat:2): WARNING **: 18:16:55.831: libsecret_error: `>\xbd\xae\xbeW
flutter: [Matrix] Unable to init database encryption - FormatException: Unexpected extension byte (at offset 2)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1741)
#1      Utf8Decoder.convert (dart:convert/utf.dart:349)
#2      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:502)
#3      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:477)
#4      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:647)
#5      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)** (fluffychat:2): WARNING **: 18:16:55.831: libsecret_error: `>\xbd\xae\xbeW
flutter: [Matrix] Unable to init database encryption - FormatException: Unexpected extension byte (at offset 2)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1741)
#1      Utf8Decoder.convert (dart:convert/utf.dart:349)
#2      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:502)
#3      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:477)
#4      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:647)
#5      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
```
and dunno if this has sth to this it, but at least its a critical error:
```
flutter: [Matrix] !!!CRITICAL!!! Client initialization failed - L10n.delegate failed to load unsupported locale "C". This is likely an issue with the localizations generation tool. Please file an issue on GitHub with a reproducible sample app and the gen-l10n configuration that was used.
#0      lookupL10n (package:flutter_gen/gen_l10n/l10n.dart:3870)
#1      flutterMatrixSdkDatabaseBuilder (package:fluffychat/utils/matrix_sdk_extensions/flutter_matrix_dart_sdk_database/builder.dart:38)
```

**Comment by mbuesch** [comment] 2024-04-02 17:42
I also get this error after upgrading to the latest fluffychat flatpak commit `263417f40349a09430afca50eae16d92072a4776dc1d9e3b2fe3531808593427`.

As a workaround, downgrading to the previous flatpak commit by executing the following command fixes fluffychat again:
```
flatpak update --commit=c256e9624c7a01f07ebad1ea30c0cf12cb5f0c154e62e9d0c179884789547290 im.fluffychat.Fluffychat
```

Is the fluffychat flatpak actually being smoke tested before release?
Completely breaking the fluffychat package has now happened multiple times.
A simple startup-smoke-test would have prevented all of them (since I use fluffychat).
So, is there a chance to get some automated pre-release smoke testing?

**Comment by shellheim** [comment] 2024-04-04 09:20
and then run :  

```
flatpak mask im.fluffychat.Fluffychat
```  

To pin the version to the previous release, so `flatpak update` ignores fluffychat until @krille-chan  fixes the issue.

**Comment by TheOneWithTheBraid** [comment] 2024-04-04 10:38
It looks like we can't parse the Locale : `C`. Your system does not have a proper Locale set and the lookup of the localization at this point fails. We should consider patching the locale lookup to be able to parse `C` as fallback to `en_US`.

**Comment by krille-chan** [comment] 2024-04-04 11:54
> I also get this error after upgrading to the latest fluffychat flatpak commit `263417f40349a09430afca50eae16d92072a4776dc1d9e3b2fe3531808593427`.
> 
> As a workaround, downgrading to the previous flatpak commit by executing the following command fixes fluffychat again:
> 
> ```
> flatpak update --commit=c256e9624c7a01f07ebad1ea30c0cf12cb5f0c154e62e9d0c179884789547290 im.fluffychat.Fluffychat
> ```
> 
> Is the fluffychat flatpak actually being smoke tested before release? Completely breaking the fluffychat package has now happened multiple times. A simple startup-smoke-test would have prevented all of them (since I use fluffychat). So, is there a chance to get some automated pre-release smoke testing?

As I by myself do not use Flatpak, no. If someone else could step up and test/maintain the Flatpak version, that would be great.

**Comment by whoizit** [comment] 2024-04-08 04:25
this is not flatpak related. I have same issue from https://aur.archlinux.org/packages/fluffychat

**Comment by soma-kurisu** [comment] 2024-04-08 19:10
same error when installing from snap

**Comment by krille-chan** [comment] 2024-04-11 13:56
> same error when installing from snap

Are you sure this is the same error? I cannot reproduce it on snap. So far I would expect this is a flatpak- and arch problem, so it is a packaging problem

**Comment by TheOneWithTheBraid** [comment] 2024-04-11 14:03
I could reproduce it everywhere where I could force kill the application - including snap. But it's hard to reproduce since you need to kill the process exactly while it's writing something into the DB.

**Comment by krille-chan** [comment] 2024-04-11 14:13
Uh okay... So you need to force-kill the app first to trigger this? It does not happen just on starting the app?

**Comment by krille-chan** [comment] 2024-04-11 14:16
Hm, I'm having a hard time reproducing this. I've now even installed the flatpak version on my ubuntu 23.10 machine, tried to force kill the application while it writes the initial sync in database, but it still works.

have to admit that the Flatpak version feels faster than the snap version btw but that's off topic :D

**Comment by mbuesch** [comment] 2024-04-11 17:37
But can you reproduce it on flatpak?
It is 100% reproducible for me and I do not have to do any tricks.
Feel free to suggest things that I can try out in my installation.

I would appreciate it, if the broken flatpak version would be yanked from the repository, if the root cause could not be found, yet.
The application is completely unusable since quite some time.
The previous version works perfectly fine.

**Comment by krille-chan** [comment] 2024-04-11 18:05
> But can you reproduce it on flatpak?
> It is 100% reproducible for me and I do not have to do any tricks.
> Feel free to suggest things that I can try out in my installation.
> 
> I would appreciate it, if the broken flatpak version would be yanked from the repository, if the root cause could not be found, yet.
> The application is completely unusable since quite some time.
> The previous version works perfectly fine.

No even with the flatpak version it works fine for me. Maybe it has something to do with the distro?

About rollback can you help there? I have no idea about flatpak and how to roll it back. The flathub config was created by somone else and then just handed over to me while actually I never wanted this responsibility...

**Comment by mbuesch** [comment] 2024-04-11 18:19
>About rollback can you help there? I have no idea about flatpak and how to roll it back.

Oh. Ok. No, I also basically don't know anything about flatpak.

>Maybe it has something to do with the distro?

The things that a flatpak inherits from the operating system should be pretty limited, right? Isn't there some kind of rules system defining exactly that?
If so, that would be the thing to look into first, IMO.
Maybe there are some environment variables that change the behavior? I can change them, if you have some suggestions.

Thanks!

**Comment by whoizit** [comment] 2024-04-12 07:42
After installing gnome-keyring the problem disappeared. No message about database and I can login with password. 

also works with keepassxc as keyring (https://www.cogitri.dev/post/03-keepassxc-freedesktop-secret/)

**Comment by shellheim** [comment] 2024-04-12 08:28
I can confirm what @whoizit says. Enabling `org.freedesktop.secrets` fixes the problem.

**Comment by soma-kurisu** [comment] 2024-04-12 08:35
> > same error when installing from snap
> 
> Are you sure this is the same error? I cannot reproduce it on snap. So far I would expect this is a flatpak- and arch problem, so it is a packaging problem

please take a look at the error message your self (attached).
![Screenshot from 2024-04-12 10-25-16](https://github.com/krille-chan/fluffychat/assets/69393463/24177f15-91fc-440e-a4b2-60961629e3bf)

if further scrutinized my systems application logs and found following entries for fluffychat:

- Causing statement: PRAGMA user_version) sql 'PRAGMA user_version' {details: {database: {path: /home/christian-sommer/snap/fluffychat/1357/.local/share/chat.fluffy.fluffychat/FluffyChat linux.sqlite, id: 1, readOnly: false, singleInstance: true}}} during open, closing...
- Causing statement: PRAGMA user_version}) DatabaseException(SqliteException(26): while selecting from statement, file is not a database, file is not a database (code 26)
- flutter: error SqfliteFfiException(sqlite_error: 26, , SqliteException(26): while selecting from statement, file is not a database, file is not a database (code 26)

**Comment by ozky84** [comment] 2024-04-12 11:43
It started to work  when i did use flatseal and gave dbus session bus priviledges to app....

**Comment by damorphh** [comment] 2024-04-12 12:10
> Can someone test it out maybe if this version fixes FluffyChat Flatpak?

Doesn't fix it on OpenSUSE Tumbleweed w/ Plasma 6. Same issue as with latest stable branch.

**Comment by damorphh** [comment] 2024-04-12 14:36
> > > Can someone test it out maybe if this version fixes FluffyChat Flatpak?
> > 
> > 
> > Doesn't fix it on OpenSUSE Tumbleweed w/ Plasma 6. Same issue as with latest stable branch.
> 
> hmm, do you have gnome keyring installed? Probably not, right? Maybe this can be fixed by allowing that the app creates an unencrypted database if secure_storage is not working

Yeah, probably. I don't have gnome keyring, and I first encountered the bug while using KDE Wallet, which I disabled to try and enable KeePassXC's secret service integration which I can't figure out lol, so right now I don't have any secure_storage client enabled.

**Comment by whoizit** [comment] 2024-04-12 20:01
> hmm, do you have gnome keyring installed? Probably not, right? Maybe this can be fixed by allowing that the app creates an unencrypted database if secure_storage is not working

I'm using full disk encryption. This will be a good decision for me. How can I disable secure_storage?

**Comment by whoizit** [comment] 2024-04-12 20:09
> I first encountered the bug while using KDE Wallet

Should work with KDE Wallet cause it [provides](https://archlinux.org/packages/?sort=&q=org.freedesktop.secrets&maintainer=&flagged=) org.freedesktop.secrets

**Comment by whoizit** [comment] 2024-04-12 20:24
I should repeat, this problem does not only apply to Flatpak, it affects any Linux distribution that does not have the Secret Service API implementation installed (standard from freedesktop.org). It's possible in any non-Gnome-KDE environments

**Comment by jane400** [comment] 2024-04-13 10:23
I feel like there are multiple issues which all relate to invalid system configuration.
- System administrators should set the locale to something using UTF-8. It's 2024. People don't tend to write code anymore, that expects something different to it.
- The `org.freedesktop.secrets` thing is actually more complicated and a more recent standardization. Not having a service which provides this API will break modern linux applications, like chromium, vscode, any application from every Toolkit which uses libsecret to store secrets. 

It's is unfortunate that gnome-keyring has the prefix `gnome-`, people should install it regardless, if they want a running system (if they configure it themselves and use sway/i3 or simiilar). It doesn't have the heaviest dependency chain for a gnome project, in comparison to KWallet which pulls in a lot of the KDE Framework.

And now to the flatpak/snap sandbox situation. You shouldn't have to proxy "org.freedesktop.secrets" from the host to the sandbox. There should be portals doing this, but these need to be configured, if the distro doesn't provide default configuration (aka using GNOME/KDE), then it has to be configured by the user: https://flatpak.github.io/xdg-desktop-portal/docs/backends.html#configuration-file

**Comment by mbuesch** [comment] 2024-04-13 11:12
>The org.freedesktop.secrets thing is actually more complicated and a more recent standardization.
>Not having a service which provides this API will break modern linux applications

Yes. And that is why all of these applications are fundamentally broken.
Especially, if they throw cryptic error messages at the user if the service is not available.

The application must either clearly say what the user has to install, or provide a fallback. I prefer the fallback.

I have a secets manager installed, because applications want it. Not because I want it.
In fact, I hate it. It constantly prompts me for entering a password, which I do not care about at all.
I don't need this stuff. Why am I forced to install it by so many applications? Just store the stuff on my already encrypted disk. It's fine.

**Comment by jane400** [comment] 2024-04-13 11:33
I'm sorry, but if you don't know how to configure your system, you 
should use a system which is already preconfigured. And if you don't 
want those dependencies, than don't use software that requires it. Aka 
not using the modern Linux desktop. Full disk encryption is not a end 
all solution to IT security. You need more than that. And do really want 
that every software implements its own solution for secrets management?

Everything needs the secret service. There is no need for the entire 
ecosystem to provide prompts that you got something wrong.

You can just start the keyring already unlocked. Then you don't have any 
prompts.

The software isn't broken. Your runtime is. Fix it or don't complain.

**Comment by mbuesch** [comment] 2024-04-13 11:45
> You need more than that. 

No, I don't.
I'm not sure why you seem to know what I need.
I certainly don't need org.freedesktop.secrets. That's a fact.

> And do really want that every software implements its own solution for secrets management?

No. Not at all. That is not what I said.
Having a central secrets management is a good thing, iff the user wants to have such a thing.

> Your runtime is. Fix it or don't complain.

My runtime isn't broken. It works fine, as I said above. I have installed a secrets manager.

But I simply don't agree with you that a secrets manager is fundamentally needed to have a working system.
Because it's not needed. And it hasn't been for decades, until recently.

It's really simple: If there is no secrets manager, then just store the data unencrypted on the disk.

But at the *very* least the application should show a *clear* error message that it depends on org.freedesktop.secrets if it is not available and explaining what to do about it.

> if you don't know how to configure your system

Could you please avoid personal attacks, that don't help the discussion in any way?
Thanks.

**Comment by TheOneWithTheBraid** [comment] 2024-04-13 12:05
The discussion is going off topic. A secrets service is essential on any Linux. It's not the upstream's job to educate users. Install a secrets service, then it's working. Under no way I'd support a fallback onto plain-text storage - as much as we would never consider this on any non-Linux system.

Declaring that we depend on a secret service is as much unnecessary as saying that a gui application requires a desktop runtime, XDG or explaining that your matrix client will need access to TCP communication.

**Comment by mbuesch** [comment] 2024-04-13 12:12
> Install a secrets service, then it's working.

How do I know, if the error message doesn't tell me?
How do I get from `Unable to build SQLite the database; Null check operator used on a Null value` to `I must install a secrets manager`?
You don't see a problem with that error message?

**Comment by NyaomiDEV** [comment] 2024-04-13 12:42
If this problem only was because the Secrets API wasn't found by FluffyChat, it doesn't mean there isn't one.

For example, in my system I run full KDE and all the other apps (Flatpaked and not flatpaked) do have access to KWallet as a Secrets provider.

Therefore I think that the problem here lies in either Secrets missing OR something else.

I double checked my locale configuration, and I have UTF-8 set up correctly. I don't use "C" anywhere. Then again, is probably Flatpak unsetting locales without me knowing? In any case, LC_*="C" is pretty much standard to use to have standardized output for logging and such. If the application doesn't support it even in a production run, it's the app's fault.

I personally solved this problem by installing FluffyChat from the AUR.

**Closed** 2024-04-13 12:48 UTC
Labels: bug, Help needed

**Comment by krille-chan** [comment] 2024-04-13 15:06
I have changed it now in the flatpak manifest and also changed the behavior of the database that it **is** from now on able to use an unencrypted database, if the connection to the gnome-keyring is not possible for any reason. In this case on start the user will be informed by a notification while a more detailed report is in the logs. I hope that is the best compromise for now. Will release a new version as a hotfix soon

**Comment by jane400** [comment] 2024-04-21 01:21
> @jane400 Actually, you _have_ to specify that the app will use `org.freedesktop.secrets`. That's how the sandboxing works. Take a look at how other apps are packaged, for example Chrom{e,ium}.

@NyaomiDEV  This shouldn't be needed, see e.g. https://gitlab.gnome.org/World/fractal#runtime-dependencies

Chromium needs this, because its chromium, but it shouldn't be the case with most apps.

**Comment by NyaomiDEV** [comment] 2024-04-21 07:08
> @NyaomiDEV  This shouldn't be needed with apps that support the new portals, see e.g. https://gitlab.gnome.org/World/fractal#runtime-dependencies

That page outlines two problems:
- You don't know if Flutter has APIs to leverage that portal you're speaking of
- In any case, everything under the sun implements Secret Service API, while only GNOME implements the portal.

Since this is literally a "we made it for ourselves" approach that is very much common for GNOME folks and enthusiasts to have, I don't see how this applies to FluffyChat at all.

**Comment by jane400** [comment] 2024-04-21 08:15
Yes, I do know. Fluffychat uses [Libsecret](https://github.com/mogol/flutter_secure_storage/blob/3bb93366161a787b07c45d8ce98c7405b40fbf1f/flutter_secure_storage_linux/linux/CMakeLists.txt#L26C1-L26C67), as flutter_secure_storage it the defacto basis in the ecosystem. Libsecret in general should be considered as a project that is probably everywhere on Linux Desktop.

> In any case, everything under the sun implements Secret Service API, while only GNOME implements the portal
Originally gnome-keyring was the only one to implement the Secrets Service API. Other projects will follow implmenting the portal too. It's in the freedesktop namespace, not in the org.gnome namespace for a reason. It's a standard.
