### ISSUE TITLE
[BUG]: Unable to play audio message

### ISSUE THREAD

**Issue by dbutti** [krille-chan/fluffychat#862] opened 2024-02-01 20:09 UTC
- Operating system: ios
- Version: 1.17.2

### Exception
MissingPluginException(No implementation found for method play on channel com.ryanheise.just_audio.methods.c903579e-c70a-4f6d-b1ec-4be96a6de509)

### StackTrace
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320)
<asynchronous suspension>
#1      MethodChannelAudioPlayer.play (package:just_audio_platform_interface/method_channel_just_audio.dart:64)
<asynchronous suspension>
#2      AudioPlayer._sendPlayRequest (package:just_audio/just_audio.dart:981)
<asynchronous suspension>

**Comment by PgBiel** [comment] 2024-02-02 03:17
seems like a duplicate of #818

**Closed** 2024-02-08 21:34 UTC
